---
- name: Remove Docker repository
  ansible.builtin.file:
    path: "/etc/yum.repos.d/docker-ce.repo"
    state: absent

- name: Add Docker repository
  ansible.builtin.get_url:
    url: "{{ containerd__docker_yum_repo_url }}"
    mode: "0644"
    dest: "/etc/yum.repos.d/docker-ce.repo"

- name: Ensure containerd is installed
  ansible.builtin.package:
    name: "containerd.io"
    state: present

- name: Ensure containerd config directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Ensure containerd modules are loaded
  ansible.builtin.copy:
    dest: "/etc/modules-load.d/containerd.conf"
    content: |
      overlay
      br_netfilter
    mode: "644"
  notify: Reload sysctl

- name: Get defaults from containerd
  ansible.builtin.command: containerd config default
  changed_when: false
  register: containerd_config_default
  when: containerd__containerd_config_default_write

- name: Prepare containerd/config.toml from default config
  ansible.builtin.copy:
    dest: /tmp/containerd_config.toml
    content: "{{ containerd_config_default.stdout }}"
    mode: "0644"
  when: containerd__containerd_config_default_write
  changed_when: false

- name: Set Cgroup driver to systemd
  ansible.builtin.lineinfile:
    regexp: "SystemdCgroup = false"
    line: "            SystemdCgroup = true"
    state: present
    path: /tmp/containerd_config.toml
  when: containerd__containerd_config_default_write
  changed_when: false

- name: Copy prepared config.toml to /etc/containerd
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
  notify: Restart containerd
  when: containerd__containerd_config_default_write

- name: Enable containerd
  ansible.builtin.service:
    name: containerd
    enabled: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Cleanup temporary file
  ansible.builtin.file:
    path: /tmp/containerd_config.toml
    state: absent
