---
- name: Unarchive helm binary
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm__version }}-linux-{{ helm__architecture_mapping.get(ansible_architecture) }}.tar.gz
    dest: /tmp
    remote_src: true
  listen: Unarchive helm binary

- name: Copy unarchived helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-{{ helm__architecture_mapping.get(ansible_architecture) }}/helm
    dest: /usr/local/bin
    mode: "0755"
    remote_src: true
  listen: Unarchive helm binary
