---
- name: Check cilium status
  ansible.builtin.command:
    cmd: "/usr/local/bin/cilium status"
  register: cilium_status
  failed_when: false
  changed_when: false

- name: Install cilium
  ansible.builtin.command:
    cmd: "/usr/local/bin/cilium install --version {{ cilium__version }}"
  register: cilium_install
  changed_when: cilium_install.rc == 0
  when: '''daemonsets.apps "cilium" not found'' in cilium_status.stdout'

- name: Check cilium status
  ansible.builtin.command:
    cmd: "/usr/local/bin/cilium status --wait"
  register: cilium_status
  changed_when: false
  failed_when: cilium_status.rc != 0
