---
- name: HUBBLE | Check hubble status
  ansible.builtin.shell:
    cmd: |
      set -e
      set -o pipefail
      /usr/local/bin/cilium status -o json | jq -r '.errors."hubble-relay"."hubble-relay".Disabled'
  register: cilium_pre_status
  changed_when: false
  tags:
    - cilium
    - cilium-hubble

- name: Print status
  ansible.builtin.debug:
    var: cilium_pre_status
  tags:
    - cilium
    - cilium-hubble

- name: HUBBLE | Enable hubble
  when: "cilium_pre_status.stdout == 'true'"
  register: enable_hubble_cmd
  changed_when: enable_hubble_cmd.rc == 0
  ansible.builtin.command:
    cmd: "/usr/local/bin/cilium hubble enable"
  tags:
    - cilium
    - cilium-hubble

- name: HUBBLE | Check hubble status
  ansible.builtin.shell:
    cmd: |
      set -e
      set -o pipefail
      /usr/local/bin/cilium status --wait -o json | jq -r '.errors."hubble-relay"."hubble-relay" | "\(.Disabled) \(.Errors)"'
  register: cilium_post_status
  changed_when: false
  failed_when: "cilium_post_status.stdout != 'false null'"
  tags:
    - cilium
    - cilium-hubble
