---
- name: CILIUM | Install needed packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - tar
      - gzip
      - jq
  tags:
    - always

- name: CILIUM | Download
  ansible.builtin.include_tasks:
    file: download-cli.yml
  tags:
    - cilium
    - cilium-download

- name: CILIUM | Install
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - cilium
    - cilium-install

- name: CILIUM | Hubble
  when: cilium__enable_hubble == true | default(false)
  ansible.builtin.include_tasks:
    file: enable-hubble.yml
  tags:
    - cilium
    - cilium-hubble
