---
- name: Check if node already joined a cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Generate join token
  ansible.builtin.command: kubeadm token create --ttl 5m --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['label_kubernetes_role_control_plane'][0] }}"
  changed_when: kubeadm_join_cmd.rc == 0
  check_mode: false
  run_once: true
  when: not kubelet_conf.stat.exists

- name: Run kubeadm join (with defaults)
  ansible.builtin.command: "{{ kubeadm_join_cmd.stdout }}"
  when: not kubelet_conf.stat.exists and kubeadm_join__join_configuration|length == 0
  register: default_join_command
  changed_when: default_join_command.rc == 0

- name: Deploy config file for kubeadm
  ansible.builtin.template:
    src: "kubeadm-config.yaml.j2"
    dest: /tmp/kubeadm-config.yaml
    mode: "0644"
  when: not kubelet_conf.stat.exists and kubeadm_join__join_configuration|length > 0

- name: Split join command
  when: not kubelet_conf.stat.exists and kubeadm_join__join_configuration|length > 0
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      echo "{{ kubeadm_join_cmd.stdout }}" | cut -d ' ' -f 3
      echo "{{ kubeadm_join_cmd.stdout }}" | cut -d ' ' -f 5
      echo "{{ kubeadm_join_cmd.stdout }}" | cut -d ' ' -f 7
  register: split_join_command
  changed_when: false
  check_mode: false

- name: Update config with join command values
  when: not kubelet_conf.stat.exists and kubeadm_join__join_configuration|length > 0
  register: enrich_join_config
  changed_when: enrich_join_config.rc == 0
  ansible.builtin.command:
    cmd: |
      /usr/local/bin/yq -i '
        .discovery.bootstrapToken.apiServerEndpoint = "{{ split_join_command.stdout_lines[0] }}" |
        .discovery.bootstrapToken.apiServerEndpoint style="double" |
        .discovery.bootstrapToken.token = "{{ split_join_command.stdout_lines[1] }}" |
        .discovery.bootstrapToken.token style="double" |
        .discovery.bootstrapToken.caCertHashes[0] = "{{ split_join_command.stdout_lines[2] }}" |
        .discovery.bootstrapToken.caCertHashes[0] style="double"
      ' /tmp/kubeadm-config.yaml

- name: Run kubeadm join (with custom config)
  ansible.builtin.command: "kubeadm join --config /tmp/kubeadm-config.yaml"
  when: not kubelet_conf.stat.exists and kubeadm_join__join_configuration|length > 0
  register: config_join_command
  changed_when: "'This node has joined the cluster' in config_join_command.stdout"

- name: Delete temp kubeadm config
  ansible.builtin.file:
    path: /tmp/kubeadm-config.yaml
    state: absent
