---
- name: Setup kubernetes worker nodes
  hosts: label_role_kubernetes
  vars_files:
    - ./vars.yml
  remote_user: "{{ personal_user }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  roles:
    - role: kubeadm_join
      vars:
        kubeadm_join__join_configuration: "{{ kubernetes_cluster_join_configuration }}"
