---
- name: Install base packages
  hosts: label_role_kubernetes
  vars_files:
    - ./vars.yml
  remote_user: "{{ personal_user }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        state: present
        name:
          - tar
          - gzip
          - jq

- name: Install k8s prerequisites
  hosts: label_role_kubernetes
  vars_files:
    - ./vars.yml
  remote_user: "{{ personal_user }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  roles:
    - containerd
    - role: wittdennis.install_helm
      vars:
        install_helm__version: "{{ helm_version }}"
    - role: install_yq
      vars:
        install_yq__version: "{{ yq_version }}"
    - role: kubeadm_install
      vars:
        kubeadm_install__kubernetes_version: "{{ kubernetes_version }}"

- name: Setup kubernetes control-node
  hosts: label_kubernetes_role_control_plane
  vars_files:
    - ./vars.yml
  remote_user: "{{ personal_user }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  roles:
    - role: kubeadm_init
      vars:
        kubeadm_init__pod_network_cidr: "{{ kubernetes_pod_cidr }}"
        kubeadm_init__version: "{{ kubernetes_version }}"
        kubeadm_init__init_configuration: "{{ kubernetes_cluster_init_configuration }}"
        kubeadm_init__cluster_configuration: "{{ kubernetes_cluster_configuration }}"
    - role: kubernetes_hcloud
      vars:
        kubernetes_hcloud__token: "{{ hcloud_token }}"
        kubernetes_hcloud__cluster_pod_cidr: "{{ kubernetes_pod_cidr }}"
        kubernetes_hcloud__network_name: "kubenet"
        kubernetes_hcloud__volume_default_location: "{{ hcloud_csi_driver_volume_default_location }}"
    - role: cilium
      vars:
        cilium__version: "{{ cilium_version }}"
        cilium__cli_version: "{{ cilium_cli_version }}"
        cilium__enable_hubble: true

- name: Setup kubernetes worker nodes
  hosts: label_role_kubernetes
  vars_files:
    - ./vars.yml
  remote_user: "{{ personal_user }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  roles:
    - role: kubeadm_join
      vars:
        kubeadm_join__join_configuration: "{{ kubernetes_cluster_join_configuration }}"
